/**
 * Fihub API Swagger
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsPermission } from './modelsPermission';


export interface ModelsRoleWithPermissions { 
    id?: string;
    name?: string;
    permissions?: Array<ModelsPermission>;
}

