/**
 * Fihub API Swagger
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ModelsRole } from './modelsRole';


export interface ModelsUserWithRoles { 
    ID?: string;
    created_at?: string;
    email?: string;
    roles?: Array<ModelsRole>;
    updated_at?: string;
}

