/**
 * Fihub API Swagger
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ModelsTransactionType = 'BUY' | 'SELL';

export const ModelsTransactionType = {
    BUY: 'BUY' as ModelsTransactionType,
    SELL: 'SELL' as ModelsTransactionType
};

