/**
 * Fihub API Swagger
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PermissionsPermission } from './permissionsPermission';


export interface RolesRoleWithPermissions { 
    id?: string;
    name?: string;
    permissions?: Array<PermissionsPermission>;
}

