/**
 * Fihub API Swagger
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransactionsTransactionType = 'BUY' | 'SELL';

export const TransactionsTransactionType = {
    BUY: 'BUY' as TransactionsTransactionType,
    SELL: 'SELL' as TransactionsTransactionType
};

