/**
 * Fihub API Swagger
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolesRoleWithPermissions } from './rolesRoleWithPermissions';


export interface UsersUserWithRoles { 
    created_at?: string;
    email?: string;
    id?: string;
    roles?: Array<RolesRoleWithPermissions>;
    updated_at?: string;
}

