/**
 * Fihub API Swagger
 *
 * Contact: contact@matthieu-freitag.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UsersUserWithPassword { 
    created_at?: string;
    email?: string;
    first_name?: string;
    id?: string;
    last_name?: string;
    password?: string;
    updated_at?: string;
}

